export const AUTHENTICATE = 'AUTHENTICATE';

export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';

export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';

export const SIGN_OUT = 'SIGN_OUT';
